### ISSUE TITLE
Connection via USB?

### ISSUE THREAD

**Issue by mconsidine** [nachoplus/pysynscan#1]
Hi,
I'm interested in playing around with this code and have a mount that does not have a WiFi module but only a wired connection via USB-to-RS232.  I can execute basic motor commands via a terminal program pointed at /dev/ttyUSB0, for example.

This code looks like it is set up for a mount with an IP address only.  Do you have any experience  with one wired off of USB?  Would a Wifi "pass thru" module be the only alternative?

Thank you.  This code looks great, particularly the variable rate tracking example.
mconsidine

**Comment by nachoplus** [comment]
Hi,

The code was inspire to command a Skywatcher AZ-GTi that has wifi. In spite of that that coudl be no hard to adapt for serial comunication. 

Sorry but I dont have time to do it but I encurage you to try it. Basicaly you have to change the sockets relate code in comm.py for the serial one.  Socket code are only in function __init__  and the _send_raw_cmd

Thank you for yout interest.
Nacho

**Comment by mconsidine** [comment]
Hi,
Thanks.  Yes, I got this sorted out.  E.g.
`import serial #MattC
import socket
import logging
import os
import select
import threading



UDP_IP = "/dev/ttyUSB0" # os.getenv("SYNSCAN_UDP_IP","192.168.4.1")
UDP_PORT = 0 # int(os.getenv("SYNSCAN_UDP_PORT",11880))

LOGGING_LEVEL=os.getenv("SYNSCAN_LOGGING_LEVEL",logging.INFO)

class comm:
    '''
    UDP Comunication module.
    Virtual. Used as base class. All members are protected
    '''
    def __init__(self,udp_ip=UDP_IP,udp_port=UDP_PORT):
        ''' Init the UDP socket '''
        if (udp_ip == "/dev/ttyUSB0"):
            print("HERE")
            print(LOGGING_LEVEL)
            logging.basicConfig(
                format='%(asctime)s %(levelname)s:synscanComm %(message)s',
                level=LOGGING_LEVEL
                )
            logging.info(f"UDP target IP: {udp_ip}")
            logging.info(f"UDP target port: {udp_port}")
            self._sock = serial.Serial('/dev/ttyUSB0', 9600, timeout=1) 
            #self._sock.setblocking(0)
            self.udp_ip=udp_ip
            self.udp_port=udp_port
            self.commOK=False
            self.lock= threading.Lock()            
        else:
            logging.basicConfig(
                format='%(asctime)s %(levelname)s:synscanComm %(message)s',
                level=LOGGING_LEVEL
                )
            logging.info(f"UDP target IP: {udp_ip}")
            logging.info(f"UDP target port: {udp_port}")
            self._sock = socket.socket(socket.AF_INET, # Internet
            socket.SOCK_DGRAM) # UDP
            self._sock.setblocking(0)
            self.udp_ip=udp_ip
            self.udp_port=udp_port
            self.commOK=False
            self.lock= threading.Lock()

    
    def _send_raw_cmd(self,cmd,timeout_in_seconds=2):
        '''Low level send command function ''' 
        if (self.udp_ip == "/dev/ttyUSB0"):
            with self.lock:   
                self._sock.write(cmd)
                ready = select.select([self._sock], [], [], timeout_in_seconds)
                if ready[0]:
                    self.commOK=True
                    max_packet = 16
                    data = self._sock.read_until(terminator='\r', size=max_packet*2)
                    #print(bytes(data))
                    response = data[len(cmd):]
                    #response = str(data[:-1])
                    print("[")
                    print(response)
                    print("]")
                    logging.debug(f"response: {response}" )
                else:
                    self.commOK=False
                    logging.debug(f"Socket timeout. {timeout_in_seconds}s without response" )
                    raise(NameError('SynscanSocketTimeoutError'))
                    response = False
        else:
            with self.lock:   
                self._sock.sendto(cmd,(self.udp_ip,self.udp_port))
                ready = select.select([self._sock], [], [], timeout_in_seconds)
                if ready[0]:
                    self.commOK=True
                    response,(fromhost,fromport) = self._sock.recvfrom(1024)
                    logging.debug(f"response: {response} host:{fromhost} port:{fromport}" )
                else:
                    self.commOK=False
                    logging.debug(f"Socket timeout. {timeout_in_seconds}s without response" )
                    raise(NameError('SynscanSocketTimeoutError'))
                    response = False        
        return response

`
There also needs to be small change at the start of motors.py as well.

This is just an initial hack.  But it passes this sequence from your README
    import synscan
    '''Goto example'''
    smc=synscan.motors()
    #Syncronize mount actual position to (0,0)
    smc.set_pos(0,0)
    #Move forward and wait to finish
    smc.goto(30,30,syncronous=True)
    #Return to original position and exit without wait
    smc.goto(0,0,syncronous=False)

Regards,
Matt

**Comment by alexw-im** [comment]
Hey @mconsidine - thanks for posting that! After a modest struggle I got this working on windows. It seems that your modifications don't directly translate since the windows PySerial stuff isn't quite as drop-in compatible with sockets, or something along those lines. Some modest hackery later and it works though.

The thing I'm still struggling with is that for some reason it's SLOOOOOOOOOOOW! Did you run into that as well? Like, using WiFi, my little "slew stop slew back" script starts right up. Over serial, there seem to be only about 10-15 commands that go by before montion starts, but the "start of comms" to "motor moving" timespan is like 20 seconds or something insane. I don't see any long waits for serial response or something like that so I'm not sure what the hangup is. Did you notice this as well?

**Comment by mconsidine** [comment]
I haven't looked at this in a long time so I'll have to revisit!  I don't recall a long delay, but I was just trying to get something to work, so I might not have noticed it.
